### ISSUE TITLE
errors from example running

### ISSUE THREAD

**Issue by wsuplantpathology** [bernardo1963/kmer_validation#1]
Hi there:

I am interested your kmer_validation method. I installed the program successfully, no errors. When I was trying to run the example, I got this error:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/lucene/util/OpenBitSet
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.util.OpenBitSet
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

The code I used is this:

`java -Xmx10G -server -jar mhap-1.5v6.jar -s test/melR6_frag_A.PB.fasta -q test/melR6_frag_B.PB.fasta --valid-kmers test/melR6_frag_AB.PB.kmer2 --no-self --num-hashes 128 --num-min-matches 3 --threshold 0.04 --weighted`

So, how to solve this issue? Thanks.

Best
Chongjing

**Comment by bernardo1963** [comment]
Dear Chongjing,

Thank you for your interest. I have not seen this error before.
If you can run the standard MHAP (Berlin et al 2015) , then your java
version probably is Ok.
 Please check if you have correctly installed the OpenBitSet.
If these two suggestions fail you will need to find  local support to fix
the problem.

best,
Bernardo

A. Bernardo Carvalho

Departamento de Genética
Universidade Federal do Rio de Janeiro
